import Head from "next/head";
import Header from "../components/Header";
import SectionContainer from "../containers/SectionContainer";
import PageContainer from "../containers/PageContainer";
import Text from "../components/Text";
import { theme } from "../assets/theme";
import Navigation from "../components/Navigation";
import { useState } from "react";
import { AnimatePresence } from "framer-motion";

export default function Home() {
  const heroTextArray = ["WE TRANSFORM", "IDEAS INTO DIGITAL", "EXPERIENCES"];

  const container = {
    hidden: { opacity: 1 },
    visible: {
      opacity: 1,
      transition: {
        delayChildren: 0.3,
        staggerChildren: 0.3,
        duration: 3,
        ease: [0.9, 0.8, 0.0, 0.4],
      },
    },
  };

  const item = {
    hidden: { y: 10, skew: -5, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      skew: 0,
    },
  };

  return (
    <div>
      <Head>
        <title>Template Minimal</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PageContainer>
        <AnimatePresence>
          <SectionContainer
            alignItems="center"
            justifyContent="center"
            flexDirection="column"
            variants={container}
            initial="hidden"
            animate="visible"
          >
            {heroTextArray.map((text, i) => {
              return (
                <Text
                  key={i}
                  fontSize="5rem"
                  text={text}
                  color={theme.colors.black}
                  variants={item}
                />
              );
            })}
          </SectionContainer>
          <SectionContainer></SectionContainer>
        </AnimatePresence>
      </PageContainer>
    </div>
  );
}
